from pydantic import BaseModel, Field
from typing import Annotated,Literal
from operator import add

class AgentSchema(BaseModel):
  messages : Annotated[list,add]=Field(...,description="List of messages send by the agent") 
  user_question : str = Field(..., description="  The Original question asked by user")
  curated_ques : str = Field(...,description="Curated user question")
  Prompt_query_context : str = Field(...,description="A detailed prompt with SQL DB context that will help agent to generate SQL Query for the user question")
  generated_sql_query : str=Field(...,description="Generated SQL Query for the user question")
  is_safe: Literal["Yes", "No"] = Field(...,description="Yes if the user question is safe and relevant to the SQL DB, No otherwise")
  comments :str =Field(...,description="Comments for the regrading sql query is safe or not")
  sql_query_execution_result : str = Field(...,description="Result of the SQL Query execution")
  final_answer : str = Field(...,description="Final answer is generated by the agent based on  user question")
  
  
from typing import Literal
from pydantic import BaseModel, Field


class JudgeSchema(BaseModel):
    answer: Literal["Yes", "No"] = Field(
        ...,
        description=(
            "Return 'Yes' if the generated SQL query is safe to execute "
            "and only performs data retrieval. Return 'No' if the query "
            "modifies, deletes, creates, or alters database data or structure."
        )
    )
    

    comments: str = Field(
        ...,
        description=(
            "Provide a brief explanation for why the SQL query was "
            "considered safe or unsafe."
        )
    )
    
    
class EtlAgentSchema(BaseModel):
    messages:Annotated[list,add]=Field(...,description="List of messages send by the ETL agent") 

    
class RouterSchema(BaseModel):
    answer:Literal["sql","etl"]=Field(...,description="sql if the user question is related to sql database else etl")
    comments:str=Field(...,description="Comments for the regrading sql query is safe or not")
    

class DataAgentSchema(BaseModel):
    messages:Annotated[list,add]=Field(...,description="List of messages to be processed  by the data agent")   
    route_response: str = ""