import os
import re
import psycopg2
from psycopg2 import sql
from psycopg2.extras import execute_values
from typing import Dict, Any, List, Optional, Set
import pandas as pd
from dotenv import load_dotenv

load_dotenv()


def get_db_config() -> Dict[str, Any]:
    """Helper to get database connection configuration from environment variables."""
    return {
        "host": os.getenv("host", "localhost"),
        "port": int(os.getenv("port", 5432)),
        "dbname": os.getenv("database", "postgres"),
        "user": os.getenv("user", "postgres"),
        "password": os.getenv("password", ""),
    }


def sanitize_session_id(session_id: Optional[str]) -> Optional[str]:
    """Sanitizes a session_id into a safe PostgreSQL identifier."""
    if not session_id or str(session_id).strip().lower() in ("default", "public", "none", "null", ""):
        return None
    safe = "".join(c for c in str(session_id).strip() if c.isalnum() or c == "_")[:60]
    return safe if safe else None


def get_session_schema_name(session_id: Optional[str]) -> Optional[str]:
    """Returns the PostgreSQL schema name for a given session_id, or None for public."""
    safe_id = sanitize_session_id(session_id)
    return f"session_{safe_id}" if safe_id else None


class DatabaseConnection:
    """
    PostgreSQL Connection Manager.
    Manages local database connections, schema extraction, structured query execution,
    and dashboard metrics.
    
    Security Architecture:
    - Queries generated by the SQL Analyst are strictly validated by deterministic syntax checks
      and the LLM Security Judge before execution.
    - Production deployments should connect with a dedicated read-only PostgreSQL role
      (e.g., GRANT SELECT ON ALL TABLES IN SCHEMA public TO readonly_user).
    """
    def __init__(self, db_config: Optional[Dict[str, Any]] = None):
        self.db_config = db_config or get_db_config()
        self.connection = None
        self._connect()

    def _connect(self):
        try:
            self.connection = psycopg2.connect(**self.db_config)
            self.connection.autocommit = True
        except Exception as e:
            print(f"Error connecting to database: {e}")
            self.connection = None

    def get_connection(self):
        """Returns a valid connection, reconnecting if closed."""
        try:
            if self.connection is None or self.connection.closed != 0:
                self._connect()
        except Exception:
            self._connect()
        return self.connection

    def schema_details(self, schema_name: str = "public") -> str:
        """Fetches detailed schema information including tables, columns, data types, and sample data."""
        connection = self.get_connection()
        if not connection:
            return "Error: Database connection is not available."

        schema_info_context = f"Database Schema : {schema_name}\n"
        cursor = None

        try:
            cursor = connection.cursor()
            cursor.execute(
                "SELECT table_name FROM information_schema.tables WHERE table_schema = %s ORDER BY table_name;",
                (schema_name,)
            )
            table_list = cursor.fetchall()

            for table in table_list:
                table_name = table[0]
                schema_info_context += f"\nTable: {table_name}\n"

                cursor.execute(
                    "SELECT column_name, data_type FROM information_schema.columns WHERE table_name = %s AND table_schema = %s ORDER BY ordinal_position;",
                    (table_name, schema_name)
                )
                column_list = cursor.fetchall()

                for column in column_list:
                    column_name = column[0]
                    data_type = column[1]
                    schema_info_context += f"  Column: {column_name}, Data Type: {data_type}\n"

                # Safely fetch sample rows using sql.Identifier
                sample_query = sql.SQL("SELECT * FROM {}.{} LIMIT 3").format(
                    sql.Identifier(schema_name),
                    sql.Identifier(table_name)
                )
                cursor.execute(sample_query)
                sample_data = cursor.fetchall()

                schema_info_context += f"  Sample Data ({len(sample_data)} rows):\n"
                for row in sample_data:
                    schema_info_context += f"    {row}\n"

        except Exception as e:
            print(f"Error in fetching schema details: {e}")
            schema_info_context = f"Error fetching schema details: {e}"
        finally:
            if cursor:
                cursor.close()

        return schema_info_context

    def get_session_tables(self, session_id: Optional[str]) -> Set[str]:
        """Returns the set of custom table names existing in the session's PostgreSQL schema."""
        schema_name = get_session_schema_name(session_id)
        if not schema_name:
            return set()

        conn = self.get_connection()
        if not conn:
            return set()

        try:
            with conn.cursor() as cur:
                cur.execute(
                    "SELECT table_name FROM information_schema.tables WHERE table_schema = %s;",
                    (schema_name,)
                )
                rows = cur.fetchall()
                return {r[0] for r in rows}
        except Exception as e:
            print(f"Error fetching session tables for {schema_name}: {e}")
            return set()

    def resolve_query_for_session(self, query: str, session_id: Optional[str]) -> str:
        """
        Rewrites a SQL query to target session-specific tables if they exist in the session schema.
        Tables not overridden in the session schema fall back to public.
        Protects SQL string literals and comments from being rewritten.
        """
        if not query or not session_id:
            return query

        session_tables = self.get_session_tables(session_id)
        if not session_tables:
            return query

        schema_name = get_session_schema_name(session_id)
        if not schema_name:
            return query

        # 1. Mask comments and string literals
        token_map = {}
        counter = [0]
        def mask_match(m):
            tok = f"___SQL_MASK_{counter[0]}___"
            counter[0] += 1
            token_map[tok] = m.group(0)
            return tok

        # Match block comments, line comments, dollar quotes, and single-quoted strings
        pattern = re.compile(
            r'(/\*[\s\S]*?\*/|--[^\r\n]*|\$[a-zA-Z0-9_]*\$[\s\S]*?\$[a-zA-Z0-9_]*\$|\'(?:[^\']|\'\')*\')'
        )
        masked = pattern.sub(mask_match, query)

        # 2. Process each overridden session table
        for tbl in session_tables:
            # A. Replace explicit public.table_name with session_schema.table_name
            pat_pub = re.compile(rf'\bpublic\.{tbl}\b', re.IGNORECASE)
            masked = pat_pub.sub(f'{schema_name}.{tbl}', masked)

            # B. Replace unqualified table references, ensuring not already session-prefixed
            pat_clause = re.compile(
                rf'(?:(,\s*)|\b(FROM|JOIN|INTO|UPDATE|TABLE)\s+)(?!(?:public|session_[a-zA-Z0-9_]+)\.)\b({tbl})\b',
                re.IGNORECASE
            )
            def make_repl(target_tbl):
                return lambda m: f"{(m.group(1) or (m.group(2) + ' '))}{schema_name}.{target_tbl}"
            masked = pat_clause.sub(make_repl(tbl), masked)

        # 3. Unmask comments and string literals
        for tok, orig in token_map.items():
            masked = masked.replace(tok, orig)

        return masked

    def execute_query(self, query: str, session_id: Optional[str] = None) -> str:
        """Executes a query and returns stringified results for the LLM."""
        res = self.execute_query_structured(query, session_id=session_id)
        if res["error"]:
            return f"SQL execution error: {res['error']}"
        return res["raw_text"]

    def execute_query_structured(self, query: str, session_id: Optional[str] = None) -> Dict[str, Any]:
        """
        Executes a validated read-only SQL query and returns column names, rows, structured dicts,
        and raw string formatting for visualization and charting without unnecessary commits.
        Automatically scopes query execution to session-isolated tables when session_id is provided.
        """
        connection = self.get_connection()
        if not connection:
            return {
                "columns": [],
                "rows": [],
                "records": [],
                "raw_text": "Error: Database connection failed.",
                "row_count": 0,
                "error": "Database connection not available."
            }

        resolved_query = self.resolve_query_for_session(query, session_id)
        cursor = None
        try:
            cursor = connection.cursor()
            cursor.execute(resolved_query)

            if cursor.description:
                columns = [desc[0] for desc in cursor.description]
                raw_rows = cursor.fetchall()

                # Convert non-serializable objects (like datetime, Decimal) to standard JSON types
                rows = []
                records = []
                for row in raw_rows:
                    clean_row = []
                    row_dict = {}
                    for col, val in zip(columns, row):
                        if hasattr(val, "isoformat"):
                            val_clean = val.isoformat()
                        elif hasattr(val, "__float__") and not isinstance(val, (int, float, bool)):
                            val_clean = float(val)
                        else:
                            val_clean = val
                        clean_row.append(val_clean)
                        row_dict[col] = val_clean
                    rows.append(clean_row)
                    records.append(row_dict)

                # Read-only query: no commit required

                return {
                    "columns": columns,
                    "rows": rows,
                    "records": records,
                    "raw_text": str(raw_rows),
                    "row_count": len(rows),
                    "error": None
                }
            else:
                connection.commit()
                return {
                    "columns": [],
                    "rows": [],
                    "records": [],
                    "raw_text": "Query executed successfully (no rows returned).",
                    "row_count": 0,
                    "error": None
                }

        except Exception as e:
            if connection:
                try:
                    connection.rollback()
                except Exception:
                    pass
            print(f"Error Executing query: {e}")
            return {
                "columns": [],
                "rows": [],
                "records": [],
                "raw_text": f"SQL execution error: {e}",
                "row_count": 0,
                "error": str(e)
            }
        finally:
            if cursor:
                cursor.close()

    def load_dataframe(self, df: pd.DataFrame, table_name: str = "weather_data") -> Dict[str, Any]:
        """
        Loads a pandas DataFrame into a PostgreSQL table using safe execute_values
        with duplicate prevention (ON CONFLICT DO UPDATE/NOTHING).
        """
        connection = self.get_connection()
        if not connection:
            return {"success": False, "error": "Database connection not available.", "rows_inserted": 0}

        cursor = None
        try:
            cursor = connection.cursor()

            # Ensure table exists with unique constraint on (city, recorded_at) for weather_data
            if table_name == "weather_data":
                cursor.execute("""
                    CREATE TABLE IF NOT EXISTS public.weather_data (
                        weather_id SERIAL PRIMARY KEY,
                        recorded_at TIMESTAMP NOT NULL,
                        city VARCHAR(100) NOT NULL,
                        latitude DECIMAL(9,6),
                        longitude DECIMAL(9,6),
                        temperature_c DECIMAL(5,2),
                        precipitation_mm DECIMAL(6,2),
                        rain_mm DECIMAL(6,2),
                        weather_code INTEGER,
                        is_rainy BOOLEAN
                    );
                    CREATE UNIQUE INDEX IF NOT EXISTS uq_weather_city_recorded ON public.weather_data(city, recorded_at);
                    CREATE INDEX IF NOT EXISTS idx_weather_recorded_at ON public.weather_data(recorded_at);
                    CREATE INDEX IF NOT EXISTS idx_weather_city ON public.weather_data(city);
                """)

            cols = [c for c in df.columns if c != "weather_id"]
            records = [tuple(x) for x in df[cols].to_numpy()]

            if table_name == "weather_data":
                insert_query = sql.SQL("""
                    INSERT INTO public.weather_data ({})
                    VALUES %s
                    ON CONFLICT (city, recorded_at) DO UPDATE SET
                        temperature_c = EXCLUDED.temperature_c,
                        precipitation_mm = EXCLUDED.precipitation_mm,
                        rain_mm = EXCLUDED.rain_mm,
                        weather_code = EXCLUDED.weather_code,
                        is_rainy = EXCLUDED.is_rainy,
                        latitude = EXCLUDED.latitude,
                        longitude = EXCLUDED.longitude;
                """).format(
                    sql.SQL(", ").join(sql.Identifier(col) for col in cols)
                )
            else:
                insert_query = sql.SQL("INSERT INTO {}.{} ({}) VALUES %s").format(
                    sql.Identifier("public"),
                    sql.Identifier(table_name),
                    sql.SQL(", ").join(sql.Identifier(col) for col in cols)
                )

            execute_values(cursor, insert_query.as_string(connection), records)
            connection.commit()

            return {
                "success": True,
                "rows_inserted": len(records),
                "table": table_name,
                "error": None
            }

        except Exception as e:
            if connection:
                try:
                    connection.rollback()
                except Exception:
                    pass
            print(f"Error loading DataFrame to {table_name}: {e}")
            return {"success": False, "error": str(e), "rows_inserted": 0}
        finally:
            if cursor:
                cursor.close()

    def get_table_data(self, table_name: str, limit: int = 50, offset: int = 0, session_id: Optional[str] = None) -> Dict[str, Any]:
        """Fetches table columns and rows for Database Explorer with pagination limit, offset, and session isolation."""
        schema_name = get_session_schema_name(session_id)
        session_tables = self.get_session_tables(session_id) if schema_name else set()
        target_schema = schema_name if table_name in session_tables else "public"
        query = f"SELECT * FROM {target_schema}.{table_name} LIMIT {limit} OFFSET {offset};"
        return self.execute_query_structured(query, session_id=session_id)

    def get_database_stats(self, session_id: Optional[str] = None) -> Dict[str, Any]:
        """Fetches high-level metrics for dashboard cards and charts scoped to the active session dataset."""
        stats = {
            "total_rides": 0,
            "total_users": 0,
            "total_vehicles": 0,
            "total_revenue": 0.0,
            "avg_rating": 0.0,
            "completed_rides": 0,
            "payment_breakdown": [],
            "rides_by_status": [],
            "top_drivers": [],
            "weather_stats": {
                "total_records": 0,
                "cities_count": 0,
                "avg_temperature": 0.0,
                "rainy_hours_count": 0,
                "city_breakdown": []
            }
        }

        try:
            # Total users
            res = self.execute_query_structured("SELECT COUNT(*) AS total FROM public.users;", session_id=session_id)
            if res["records"]:
                stats["total_users"] = int(res["records"][0].get("total", 0))

            # Total rides & completed rides
            res = self.execute_query_structured("SELECT COUNT(*) AS total, COALESCE(SUM(CASE WHEN status ILIKE 'completed' THEN 1 ELSE 0 END), 0) AS completed FROM public.rides;", session_id=session_id)
            if res["records"]:
                stats["total_rides"] = int(res["records"][0].get("total", 0))
                stats["completed_rides"] = int(res["records"][0].get("completed", 0))

            # Total vehicles
            res = self.execute_query_structured("SELECT COUNT(*) AS total FROM public.vehicles;", session_id=session_id)
            if res["records"]:
                stats["total_vehicles"] = int(res["records"][0].get("total", 0))

            # Total revenue (completed & successful transactions)
            res = self.execute_query_structured("SELECT COALESCE(SUM(amount), 0) AS revenue FROM public.payments WHERE payment_status ILIKE '%success%' OR payment_status ILIKE '%complet%';", session_id=session_id)
            if res["records"]:
                stats["total_revenue"] = float(res["records"][0].get("revenue", 0))

            # Average rating
            res = self.execute_query_structured("SELECT COALESCE(AVG(rating), 0) AS avg_rating FROM public.ratings;", session_id=session_id)
            if res["records"]:
                stats["avg_rating"] = round(float(res["records"][0].get("avg_rating", 0)), 2)

            # Payment breakdown
            res = self.execute_query_structured("SELECT payment_method, COUNT(*) AS count, COALESCE(SUM(amount), 0) AS total FROM public.payments GROUP BY payment_method ORDER BY count DESC;", session_id=session_id)
            stats["payment_breakdown"] = res["records"]

            # Rides by status
            res = self.execute_query_structured("SELECT status, COUNT(*) AS count FROM public.rides GROUP BY status ORDER BY count DESC;", session_id=session_id)
            stats["rides_by_status"] = res["records"]

            # Top 5 drivers
            res = self.execute_query_structured("""
                SELECT u.first_name || ' ' || u.last_name AS driver_name,
                       ROUND(AVG(r.rating)::numeric, 2) AS avg_rating,
                       COUNT(r.rating_id) AS total_reviews
                FROM public.ratings r
                JOIN public.users u ON r.driver_id = u.user_id
                GROUP BY u.user_id, u.first_name, u.last_name
                ORDER BY avg_rating DESC, total_reviews DESC
                LIMIT 5;
            """, session_id=session_id)
            stats["top_drivers"] = res["records"]

            # Weather statistics
            w_res = self.execute_query_structured("""
                SELECT 
                    COUNT(*) AS total_records,
                    COUNT(DISTINCT city) AS cities_count,
                    ROUND(AVG(temperature_c)::numeric, 1) AS avg_temperature,
                    COALESCE(SUM(CASE WHEN is_rainy THEN 1 ELSE 0 END), 0) AS rainy_hours_count
                FROM public.weather_data;
            """, session_id=session_id)
            if w_res["records"]:
                stats["weather_stats"]["total_records"] = w_res["records"][0].get("total_records", 0)
                stats["weather_stats"]["cities_count"] = w_res["records"][0].get("cities_count", 0)
                stats["weather_stats"]["avg_temperature"] = float(w_res["records"][0].get("avg_temperature", 0) or 0)
                stats["weather_stats"]["rainy_hours_count"] = w_res["records"][0].get("rainy_hours_count", 0)

            # City weather breakdown
            w_city = self.execute_query_structured("""
                SELECT 
                    city,
                    ROUND(AVG(temperature_c)::numeric, 1) AS avg_temp,
                    ROUND(AVG(rain_mm)::numeric, 2) AS avg_rain_mm,
                    ROUND(SUM(precipitation_mm)::numeric, 1) AS total_precip_mm,
                    SUM(CASE WHEN is_rainy THEN 1 ELSE 0 END) AS rainy_hours
                FROM public.weather_data
                GROUP BY city
                ORDER BY city;
            """, session_id=session_id)
            stats["weather_stats"]["city_breakdown"] = w_city["records"]

        except Exception as e:
            print(f"Error fetching database stats: {e}")

        return stats


if __name__ == "__main__":
    obj = DatabaseConnection()
    result = obj.schema_details("public")
    print("Schema Details Length:", len(result))
    stats = obj.get_database_stats()
    print("Database Stats:", stats)
